In [1]:
import pandas as pd
import numpy as np

In [3]:
a = 3
b = 4
c = a + b
c

7

In [8]:
data = np.arange(1,10).reshape(3,3)

In [9]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([6,7,8,9,10])

In [11]:
dt1 = np.concatenate([ar1,ar2], axis = 0)

In [9]:
dt1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
df2 = dt1.reshape((2,5))

In [13]:
df2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
ar3 = np.random.randint(1,10, size=(2,5))

In [18]:
ar3

array([[2, 7, 8, 6, 4],
       [9, 8, 1, 4, 2]])

In [26]:
dt3 = np.concatenate([df2,ar3])

In [27]:
dt3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 2,  7,  8,  6,  4],
       [ 9,  8,  1,  4,  2]])

In [28]:
df4= np.concatenate([df2,ar3], axis = 1)

In [29]:
df4

array([[ 1,  2,  3,  4,  5,  2,  7,  8,  6,  4],
       [ 6,  7,  8,  9, 10,  9,  8,  1,  4,  2]])

In [31]:
np.array([range(i, i+5) for i in [1, 4, 7]])

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 7,  8,  9, 10, 11]])

In [36]:
aa = []
for i in [1,2,3]:
    aa.append(i * 10)

In [37]:
aa

[10, 20, 30]

In [38]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [42]:
np.linspace(10,100,5, dtype=(int))

array([ 10,  32,  55,  77, 100])

In [43]:
np.random.randint(0,10, (3,3))

array([[4, 6, 4],
       [4, 9, 9],
       [7, 8, 2]])

In [47]:
np.random.normal(0,1,(3,3))

array([[-1.6228163 , -0.82796377, -2.37380969],
       [ 0.21764861, -0.86714601, -1.54131886],
       [ 1.18541938, -0.41788523, -0.80586997]])

In [11]:
c1 = np.array([1,2,3])

In [12]:
c1

array([1, 2, 3])

In [14]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.array(data)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.array([range(i, i+8) for i in [10,20,30]])

array([[10, 11, 12, 13, 14, 15, 16, 17],
       [20, 21, 22, 23, 24, 25, 26, 27],
       [30, 31, 32, 33, 34, 35, 36, 37]])

In [30]:
np.linspace(10,100,5, dtype = (int))

array([ 10,  32,  55,  77, 100])

In [35]:
np.full((3,2),6)

array([[6, 6],
       [6, 6],
       [6, 6]])

In [41]:
np.ones((2,3), dtype=(int))

array([[1, 1, 1],
       [1, 1, 1]])

In [42]:
l1 = [1,2,3]
l2 = [4,5,6]

In [47]:
aa = np.concatenate([l1,l2])

In [48]:
aa

array([1, 2, 3, 4, 5, 6])

In [56]:
bb1 = np.arange(1,13).reshape(3,4)

In [58]:
bb2 = np.arange(11,23).reshape(3,4)

In [62]:
cc1=np.concatenate([bb1,bb2],axis = 1)

In [81]:
cc2=np.concatenate([bb1,bb2],axis = 0)

In [82]:
dd1 = np.vstack(cc2).sum()

In [100]:
cc2 =np.ones((2,6))

In [103]:
cc2

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [101]:
dd3 = np.sum(cc2, axis=0)

In [104]:
dd4 = np.sum(cc2, axis=1)

In [106]:
dd3,dd4

(array([2., 2., 2., 2., 2., 2.]), array([6., 6.]))

In [94]:
dd2 = np.sum(cc2, axis=0)

In [95]:
dd2

array([60, 66, 72, 78])

In [97]:
cc2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])